### ISSUE TITLE
[Feature] Integrate SonarQube with Maven and Run GitHub Actions

### ISSUE THREAD

**Issue by Lokankara** [RedRoverSchool/JenkinsQA_2024_spring#1578]
## User Story
**As a** admin  
**I want to** integrate SonarQube with Maven and run it within GitHub Actions  
**So that** I can automatically analyze code quality and ensure code standards are maintained  

## Assumptions & Constraints
- SonarQube server is accessible and properly configured 
- The Maven project is correctly set up with necessary dependencies.
- GitHub Actions workflows are configured to trigger on relevant events (e.g., push, pull request).

## Preconditions
- A SonarQube server is running and accessible (https://sonarcloud.io/).
- SonarQube token is available for authentication.
- Maven project with a valid `pom.xml` file.
- GitHub repository with workflows set up.

## Business Rules
- Code should meet defined quality standards before being merged.
- Quality gate in SonarQube should be configured to enforce code quality rules.
- SonarQube analysis should run automatically on each push and pull request.

## Acceptance Criteria
1. **SonarQube Integration**
   - Given a Maven project, when a developer runs a build, then the project should be analyzed by SonarQube.
   
2. **GitHub Actions Workflow**
   - Given a push or pull request event, when the GitHub Actions workflow is triggered, then it should run the SonarQube analysis as part of the CI pipeline.
   
3. **Quality Gate Enforcement**
   - Given the SonarQube analysis, when the quality gate conditions are not met, then the workflow should fail, and a notification should be sent.

### SonarQube Integration with Maven
1. **Add SonarQube Plugin to Maven**
   - Update `pom.xml` to include the SonarQube Maven plugin:
     ```xml
     <plugin>
         <groupId>org.sonarsource.scanner.maven</groupId>
         <artifactId>sonar-maven-plugin</artifactId>
         <version>3.9.0.2155</version>
     </plugin>
    <properties>
         <sonar.host.url>https://sonarcloud.io</sonar.host.url>
        <sonar.organization>organization_key</sonar.organization>
        <sonar.projectKey>project_key</sonar.projectKey>
      </properties>
     ```
or 

2. **Configure SonarQube Properties**
   - Add `sonar-project.properties` file or update the `pom.xml` with SonarQube properties:
     ```properties
     sonar.projectKey=project_key
     sonar.host.url=https://sonarcloud.io
     sonar.login=sonarqube_token
     ```

### GitHub Actions Workflow Configuration
1. **Create GitHub Actions Workflow File**
   - Create a workflow file (e.g., `.github/workflows/sonar.yml`):
     ```yaml
     name: SonarCloud Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and analyze with SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          run: mvn clean verify sonar:sonar
     ```

### Quality Gate Configuration
1. **Set Up Quality Gate in SonarQube**
   - Define quality gate rules in SonarQube to enforce code quality standards.
   - Ensure the quality gate is associated with the project.

### Testing
1. **Verify Maven Build and SonarQube Analysis Locally**
   - Run the Maven build with SonarQube analysis locally to ensure it works:
     ```bash
     mvn clean verify sonar:sonar
     ```

2. **Trigger GitHub Actions Workflow**
   - Push changes to the repository or create a pull request to trigger the GitHub Actions workflow.
   - Verify that the SonarQube analysis runs and the results are reported.
